name: test postgres-extras-clj

on: [push]

jobs:

  clojure:

    strategy:
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-dep: 0

      - name: Prepare java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          # Be conservative with Java version
          java-version: '8'

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@12.5
        with:
          # Clojure is stable enough to run off latest
          cli: 'latest'
          clj-kondo: 'latest'
          
      - name: Cache clojure dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
            ~/.gitlibs
          key: cljdeps-${{ hashFiles('deps.edn') }}
          restore-keys: cljdeps-

      - name: Linting
        run: clj-kondo --lint src test examples --debug

      - name: Run tests
        run: clojure -X:test
        
      - name: Build jar
        run: clojure -T:build jar

      - name: Push to clojars if tagged
        if: contains(github.ref, '/tags/v')
        run: clojure -T:build deploy

